[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.13"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
comptoken = "F9SW7dcgDHV6QGYcFHyqKtykAdsHvL4BJYA2YP4YkEJX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
