name: Run Tests on Pull Request
on: pull_request
jobs:
    rust-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # adapted from https://github.com/metaDAOproject/setup-solana/blob/v1.0/action.yml
            - name: Install Solana CLI tools
              run: curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/solana-developers/solana-install/main/install.sh | bash
              shell: bash
            - name: Update PATH
              run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
              shell: bash
            # end of adapted code

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Run rust tests
              run: cargo test-sbf

    component-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # adapted from https://github.com/metaDAOproject/setup-solana/blob/v1.0/action.yml
            - name: Install Solana CLI tools
              run: curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/solana-developers/solana-install/main/install.sh | bash
              shell: bash
            - name: Update PATH
              run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
              shell: bash
            # end of adapted code

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # it doesn't work with 3.10, don't know about 3.11

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install js dependencies
              run: npm clean-install --prefix ./test/compto-test-client

            - name: run component tests
              run: python3 test/component_tests.py # calls node.js scripts to run tests

    integration-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # adapted from https://github.com/metaDAOproject/setup-solana/blob/v1.0/action.yml
            - name: Install Solana CLI tools
              run: curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/solana-developers/solana-install/main/install.sh | bash
              shell: bash
            - name: Update PATH
              run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
              shell: bash
            # end of adapted code

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # it doesn't work with 3.10, don't know about 3.11

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install js dependencies
              run: npm clean-install --prefix ./test/compto-test-client

            - name: run integration tests
              run: python3 test/full_deploy_test.py
