name: Run Tests on Pull Request
on: pull_request
jobs:
    rust-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Solana
              id: setup-solana
              uses: ./.github/actions/setup-solana
              with:
                  solana-cli-version: "2.1.20"

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Run rust tests
              run: cargo test-sbf

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Solana
              uses: ./.github/actions/setup-solana
              with:
                  solana-cli-version: "2.1.20"

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # it doesn't work with 3.10, don't know about 3.11

            - name: Generate program keypairs
              run: |
                  mkdir -p target/deploy
                  solana-keygen new --no-bip39-passphrase --silent --outfile target/deploy/comptoken-keypair.json
                  solana-keygen new --no-bip39-passphrase --silent --outfile target/deploy/comptoken_transfer_hook-keypair.json
                  solana-keygen new --no-bip39-passphrase --silent --outfile test/.cache/comptoken_mint-keypair.json

            - name: build with validator
              run: |
                  export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
                  python3 test/build_comptoken_program.py --features testmode

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: comptoken-build
                  include-hidden-files: true
                  path: |
                      target/deploy/*
                      comptoken/src/generated/comptoken_generated.rs
                      comptoken-transfer-hook/src/generated/comptoken_generated.rs
                      test/.cache/*

    component-tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Solana
              uses: ./.github/actions/setup-solana
              with:
                  solana-cli-version: "2.1.20"

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: comptoken-build

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # it doesn't work with 3.10, don't know about 3.11

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install js dependencies
              run: npm clean-install --prefix ./test/compto-test-client

            - name: run component tests
              run: python3 test/component_tests.py --no-build --no-reset # calls node.js scripts to run tests; do not reset the validator

    integration-tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Solana
              uses: ./.github/actions/setup-solana
              with:
                  solana-cli-version: "2.1.20"

            - name: Generate keypair
              run: solana-keygen new --no-bip39-passphrase --silent

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: comptoken-build

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # it doesn't work with 3.10, don't know about 3.11

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install js dependencies
              run: npm clean-install --prefix ./test/compto-test-client

            - name: run integration tests
              run: python3 test/full_deploy_test.py --no-build --no-reset -vvv # calls node.js scripts to run tests; do not reset the validator

            - name: Validator logs on failure
              if: failure()
              run: |
                  echo "Validator logs:"
                  cat test/.cache/test-ledger/validator.log
                  echo "Solana CLI version:"
                  solana --version
                  echo "Solana config:"
                  solana config get
